version: '3'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /usr/src/app
    tty: true
    volumes:
      - .:/usr/src/app
    environment:
      HOST: 0.0.0.0 
      PORT: 8080
      MONGO_URI: "mongodb://mongo:27017/rtms"
    ports:
      - '8080:8080'
    networks:
      - app_network

  mongo:
    image: mongo:4.2
    ports:
      - '27017:27017'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
